"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7ig=26g)#$xgr#m&r_oo^@60(7yag6i*a!vw&mylcoc(y=qksj'

# SECURITY WARNING: don't run with debug turned on in production!
# 生成环境下需要关闭DEBUG
DEBUG = False

# 可访问的郁闷
ALLOWED_HOSTS = ['127.0.0.1','localhost','.shugaocheng.win']



# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account',
    'shop',
    'shoppingcart',
    'orders',
    'sorl.thumbnail',  # 缩略图
    'celery',
    'coupons',    # 优惠劵
    'rest_framework', # API接口
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware', # 会话
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',   # 更改admin站点语言显示

)

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shoppingcart.context_processors.shopping_cart',    # 自定义上下文
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3')
        'NAME': 'shop',
        'USER': 'root',
        'PASSWORD': 'wp1993524.',
        'HOST': 'localhost',
        'PORT': '3306'
        }

    }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
# 替换,可以使用中文

TIME_ZONE = 'Asia/Shanghai'

LANGUAGE_CODE = 'zh-cn'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# 静态路径配置
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')

# 设置图片保存路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# 缩略图调试
THUMBNAIL_DEBUG = True
# 购物车会话id
CART_SESSION_ID = 'shopping_cart'
CART_SESSION_NAME = 'username'

# 邮箱配置:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST='smtp.163.com' #SMTP服务器
EMAIL_PORT = 25           #SMTP端口
EMAIL_HOST_USER = 'shugaocheng@163.com' #用该邮箱发邮件，邮箱必须有效
EMAIL_HOST_PASSWORD = 'wp1993524'  #邮箱密码，必须正确
EMAIL_USE_TLS = True           #与SMTP服务器通信时，是否启动TLS连接（安全连接），默认为false
EMAIL_TO_RECEIPT = ['shugaocheng@163.com','70016803@qq.com']


from django.core.urlresolvers import reverse_lazy
LOGIN_REDIRECT_URL = reverse_lazy('shop:product_list')
LOGIN_URL = reverse_lazy('account:login')
LOGOUT_URL = reverse_lazy('account:logout1')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}
CACHE_BACKEND = 'db://my_cache_table'

# 缓存
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# redis数据库配置
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1


# rest配置
REST_FRAMEWORK = {
    # 该配置指定了去读取,创建,更新或者删除对象的默认权限
    # 设置DjangoModelPermissionsOrAnonReadOnly作为唯一的默认权限类。
    # 这个类依赖与Django的权限系统允许用户去创建，更新，或者删除对象，
    # 同时提供只读的访问给陌生人用户
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}